"use client";

import { useState } from "react";
import { Play, Zap, Power, Server, RotateCw, Lock, Terminal, Copy, Check } from "lucide-react";
import { ActionButton } from "@/components/ActionButton";
import { DataTable } from "@/components/DataTable";
import { MetricCard } from "@/components/MetricCard";
import { StatusBadge } from "@/components/StatusBadge";
import { useData } from "@/context/DataContext";
import { useAuth } from "@/context/AuthContext";

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const copy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button
      type="button"
      onClick={copy}
      title="Copy command"
      style={{
        display: "flex",
        alignItems: "center",
        gap: "4px",
        padding: "4px 8px",
        borderRadius: "4px",
        cursor: "pointer",
        fontSize: "11px",
        fontFamily: "var(--font-data)",
        background: copied ? "rgba(74,222,128,0.12)" : "rgba(255,255,255,0.05)",
        border: `1px solid ${copied ? "rgba(74,222,128,0.3)" : "var(--border)"}`,
        color: copied ? "var(--success)" : "var(--muted)",
        flexShrink: 0,
      }}
    >
      {copied ? <Check size={11} /> : <Copy size={11} />}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

export default function ScalingPage() {
  const { scalingEvents, addScalingEvent } = useData();
  const { user } = useAuth();
  const role = user?.role || "viewer";

  const [selectedAction, setSelectedAction] = useState("start");
  const [reason, setReason] = useState("Manual operator override for AWS EC2 instance scaling.");
  const [loadingAction, setLoadingAction] = useState(false);
  const [actionFeedback, setActionFeedback] = useState<{ message?: string; error?: string } | null>(null);

  const handleScalingSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoadingAction(true);
    setActionFeedback(null);

    try {
      const res = await fetch("/api/scaling/action", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: selectedAction, role }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || "AWS Scaling action failed");
      }

      setActionFeedback({ message: data.message });

      // Add to scaling decisions list
      addScalingEvent({
        id: `evt-aws-${Date.now()}`,
        resourceId: "AWS EC2 t3.micro (us-east-1)",
        policyId: "AWS-EC2-Target-CPU-70%",
        type: selectedAction === "start" ? "scale_up" : "scale_down",
        cloudProvider: "aws",
        region: "us-east-1",
        status: "success",
        reason: `${reason} (${user?.displayName || "Operator"})`,
        timestamp: new Date().toLocaleTimeString(),
      });
    } catch (err: any) {
      setActionFeedback({ error: err.message });
    } finally {
      setLoadingAction(false);
    }
  };

  return (
    <div className="page">
      <header className="page-heading">
        <div>
          <h1>AWS Cloud Auto-Scaling Engine</h1>
          <p>Real-world EC2 capacity control, AWS SDK scaling execution, and policy decision logs.</p>
        </div>
      </header>

      {/* KPI Cards */}
      <section className="grid kpis">
        <MetricCard label="AWS Region" value="us-east-1" trend="N. Virginia Region" icon={<Server size={18} />} />
        <MetricCard label="Target Machine" value="EC2 t3.micro" trend="Live AWS Server" icon={<Play size={18} />} />
        <MetricCard label="Target Scaling Rule" value="Target CPU 70%" trend="Active Policy" icon={<Zap size={18} />} />
        <MetricCard label="Current Operator" value={role.toUpperCase()} trend={user?.displayName || "Authenticated"} icon={<Power size={18} />} />
      </section>

      <section className="grid two">
        {/* Scaling Events Log */}
        <div className="panel">
          <h2>Recent AWS Scaling Decisions</h2>
          <p style={{ fontSize: "12px", color: "var(--faint)", marginBottom: "14px" }}>
            Real-time decision logs generated by AWS CloudWatch metrics and operator commands.
          </p>
          <DataTable
            rows={scalingEvents}
            columns={[
              { key: "type", header: "Decision" },
              { key: "resourceId", header: "Resource" },
              { key: "policyId", header: "Policy" },
              { key: "region", header: "Region" },
              { key: "status", header: "Status", render: (row) => <StatusBadge value={String(row.status)} /> },
              { key: "reason", header: "Trigger" },
            ]}
          />
        </div>

        {/* AWS Scaling Action Form */}
        <div className="panel">
          <h2>Direct AWS Instance Scaling Control</h2>
          <p style={{ fontSize: "12px", color: "var(--faint)", marginBottom: "14px" }}>
            Issue real-time Start, Stop, or Reboot commands directly to your connected AWS EC2 instance.
          </p>

          {(role === "viewer" || role === "pending" || role === "developer") ? (
            <div style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              gap: "12px",
              padding: "40px 20px",
              border: "1px dashed var(--line)",
              borderRadius: "8px",
              textAlign: "center",
              color: "var(--faint)",
            }}>
              <Lock size={28} style={{ opacity: 0.4 }} />
              <div>
                <p style={{ fontWeight: 600, marginBottom: "4px", color: "var(--foreground)" }}>Access restricted</p>
                <p style={{ fontSize: "12px" }}>Only Operators, Admins, and Super Admins can execute AWS scaling commands.</p>
              </div>
            </div>
          ) : (
            <>
              {actionFeedback?.message && (
                <div style={{ padding: "10px 14px", borderRadius: "6px", background: "rgba(34, 197, 94, 0.15)", border: "1px solid rgba(34, 197, 94, 0.3)", color: "#4ade80", fontSize: "13px", marginBottom: "14px" }}>
                  ✓ {actionFeedback.message}
                </div>
              )}

              {actionFeedback?.error && (
                <div style={{ padding: "10px 14px", borderRadius: "6px", background: "rgba(239, 68, 68, 0.15)", border: "1px solid rgba(239, 68, 68, 0.3)", color: "#f87171", fontSize: "13px", marginBottom: "14px" }}>
                  ⚠ {actionFeedback.error}
                </div>
              )}

              <form onSubmit={handleScalingSubmit} className="form-grid">
                <label className="field span-2">
                  Target AWS Resource
                  <select disabled>
                    <option>AWS EC2 t3.micro (us-east-1) - Connected</option>
                  </select>
                </label>

                <label className="field span-2">
                  Scaling Command Action
                  <select value={selectedAction} onChange={(e) => setSelectedAction(e.target.value)}>
                    <option value="start">Start EC2 Instance (Scale Up / Boot)</option>
                    <option value="stop">Stop EC2 Instance (Scale Down / Power Off)</option>
                    <option value="reboot">Reboot EC2 Instance (Restart Service)</option>
                  </select>
                </label>

                <label className="field span-2">
                  Operator Reason
                  <textarea
                    value={reason}
                    onChange={(e) => setReason(e.target.value)}
                    rows={2}
                  />
                </label>

                <button
                  type="submit"
                  disabled={loadingAction}
                  className="button span-2"
                  style={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    gap: "8px",
                    background: "linear-gradient(135deg, #ff9900, #e68a00)",
                    color: "#000",
                    padding: "12px",
                    fontWeight: 700,
                    borderRadius: "8px",
                  }}
                >
                  {loadingAction ? <RotateCw size={16} className="spin" /> : <Zap size={16} />}
                  {loadingAction ? "Dispatching to AWS..." : "Execute AWS Action"}
                </button>
              </form>
            </>
          )}
        </div>
      </section>

      {/* EC2 Terminal Commands (top -b & force kill) */}
      <section className="stress-panel" style={{ marginTop: "16px", borderTop: "2px solid var(--primary)" }}>
        <div className="section-head" style={{ marginBottom: "12px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "7px" }}>
            <Terminal size={15} style={{ color: "var(--primary)" }} />
            <h2>EC2 Terminal Diagnostic & Power Commands</h2>
          </div>
          <span style={{ fontSize: "11px", fontFamily: "var(--font-data)", color: "var(--faint)" }}>
            Run inside Ubuntu SSH Session
          </span>
        </div>
        <p style={{ margin: "0 0 10px", fontSize: "11px", color: "var(--faint)" }}>
          Real system commands to run in your Ubuntu EC2 terminal to monitor CPU usage, terminate processes, or halt the machine.
        </p>

        <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
          <div className="stress-cmd">
            <div style={{ minWidth: 0 }}>
              <div style={{ fontFamily: "var(--font-data)", fontSize: "11px", color: "var(--text)", marginBottom: "2px" }}>
                Inspect Live CPU & Processes (top batch snapshot)
              </div>
              <code style={{ fontSize: "10px", color: "var(--faint)" }}>
                Runs top in batch mode (-b) for 1 iteration (-n 1) and displays the first 15 lines of real CPU & task load.
              </code>
            </div>
            <CopyButton text="top -b -n 1 | head -n 15" />
          </div>

          <div className="stress-cmd">
            <div style={{ minWidth: 0 }}>
              <div style={{ fontFamily: "var(--font-data)", fontSize: "11px", color: "var(--text)", marginBottom: "2px" }}>
                Force Terminate All Stress Processes (Emergency Stop)
              </div>
              <code style={{ fontSize: "10px", color: "var(--faint)" }}>
                Sends SIGKILL (-9) to immediately stop all background yes, python, while loops, and stress utilities.
              </code>
            </div>
            <CopyButton text='sudo pkill -9 yes; sudo pkill -9 -f "while true"; sudo pkill -9 python3; sudo pkill -9 stress' />
          </div>

          <div className="stress-cmd">
            <div style={{ minWidth: 0 }}>
              <div style={{ fontFamily: "var(--font-data)", fontSize: "11px", color: "var(--text)", marginBottom: "2px" }}>
                Power Off / Stop EC2 (Inside SSH - No AWS CLI Needed)
              </div>
              <code style={{ fontSize: "10px", color: "var(--faint)" }}>
                Standard Linux system command to power off the VM immediately. AWS detects it as stopped.
              </code>
            </div>
            <CopyButton text="sudo poweroff" />
          </div>

          <div className="stress-cmd">
            <div style={{ minWidth: 0 }}>
              <div style={{ fontFamily: "var(--font-data)", fontSize: "11px", color: "var(--text)", marginBottom: "2px" }}>
                Reboot EC2 (Inside SSH - No AWS CLI Needed)
              </div>
              <code style={{ fontSize: "10px", color: "var(--faint)" }}>
                Standard Linux command to reboot the VM directly from inside your SSH session.
              </code>
            </div>
            <CopyButton text="sudo reboot" />
          </div>
        </div>
      </section>
    </div>
  );
}
